MvcKamp/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MvcKamp.Controllers
{
    public class WriterController : Controller
    {
        private WriterManager writerManager = new WriterManager(new EfWriterDal());
        WriterValidator writerValidatior = new WriterValidator();

        // GET: Writer

        public ActionResult Index()
        {
            var writerValues = writerManager.getList();
            return View(writerValues);
        }

        [HttpGet]
        public ActionResult AddWriter()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddWriter(Writer writer)
        {
           
            ValidationResult results = writerValidatior.Validate(writer);
            if (results.IsValid)
            {
                writerManager.add(writer);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName,item.ErrorMessage);
                }
            }
            return View();
            
        }
        [HttpGet]
        public ActionResult UpdateWriter(int id)
        {
            var writerValues = writerManager.getById(id);
            return View(writerValues);
        }
        [HttpPost]
        public ActionResult UpdateWriter(Writer writer)
        {
            ValidationResult results = writerValidatior.Validate(writer);
            if (results.IsValid)
            {
                writerManager.update(writer);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }
    }
}

MvcKamp/Views/Writer/AddWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazar Ekle</h2>
<br />
@using (Html.BeginForm("AddWriter", "Writer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
        <br />
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurName)
        <br />
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
        <br />
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword)
        <br/>
        @Html.Label("Yazar Görsel Linki")
        @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br />
        @Html.Label("Yazar Ünvan")
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        @Html.Label("Yazar Hakkkımda")
        @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
        <br />
        <button class="btn btn-success">Ekle</button>
    </div>
}

MvcKamp/Views/Writer/Index.cshtml
@using EntityLayer.Concrete;
@model List<Writer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
  
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Yazarlar</h1>
                        </div>
                     
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card card-solid">
                    <div class="card-body pb-0">
                        <div class="row d-flex align-items-stretch">
                            @foreach (var item in Model)
                            {
                                <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                    <div class="card bg-light">
                                        <div class="card-header text-muted border-bottom-0">
                                            @item.WriterTitle
                                        </div>
                                        <div class="card-body pt-0">
                                            <div class="row">
                                                <div class="col-7">
                                                    <h2 class="lead"><b>@item.WriterName @item.WriterSurName</b></h2>
                                                    <p class="text-muted text-sm"><b>Hakkımda: </b> @item.WriterAbout </p>
                                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-file-contract"></i></span> Email: @item.WriterMail</li>
                                                        
                                                    </ul>
                                                </div>
                                                <div class="col-5 text-center">
                                                    <img src="@item.WriterImage" alt="" class="img-circle img-fluid">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card-footer">
                                            <div class="text-right">
                                                <a href="#" class="btn btn-sm bg-teal">
                                                    <i class="fas fa-comments">Yazarın Başlıkları</i>
                                                </a>
                                                <a href="/Writer/UpdateWriter/@item.WriterId" class="btn btn-sm btn-primary">
                                                    <i class="fas fa-user"></i> Profili Düzenle
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                 
                </div>
                <!-- /.card -->

            </section>

</body>
</html>

MvcKamp/Views/Writer/UpdateWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "UpdateWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yazar Güncelleme</h2>
@using (Html.BeginForm("UpdateWriter", "Writer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Yazar Id")
        @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new {@class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterName)
        <br/>
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurName, new {@class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterSurName)
        <br/>
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new {@class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterMail)
        <br/>
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(x => x.WriterPassword, new {@class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterPassword)
        <br/>
        @Html.Label("Yazar Görsel Linki")
        @Html.TextBoxFor(x => x.WriterImage, new {@class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br/>
        @Html.Label("Yazar Ünvanı ")
        @Html.TextBoxFor(x => x.WriterTitle, new {@class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br/>
        @Html.Label("Yazar Hakkkımda")
        @Html.TextBoxFor(x => x.WriterAbout, new {@class = "form-control"})
        @Html.ValidationMessageFor(x => x.WriterAbout)
        <br/>
        <button class="btn btn-success">Güncelle</button>
    </div>
}