MvcKamp/Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;

namespace MvcKamp.Controllers
{
    [AllowAnonymous]
    public class AuthorizationController : Controller
    {
        private AdminManager adminManager = new AdminManager(new EfAdminDal());

        public ActionResult Index()
        {
            var adminValues = adminManager.getList();
            return View(adminValues);
        }
        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(Admin admin)
        {
            adminManager.add(admin);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateAdmin(int id)
        {
            var adminValues = adminManager.getById(id);
            return View(adminValues);
        }

        [HttpPost]
        public ActionResult UpdateAdmin(Admin admin)
        {
            adminManager.update(admin);
            return RedirectToAction("Index");
        }
    }
}

MvcKamp/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kullanıcı Adı")
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <br />
    @Html.Label("Şifre")
    @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
    <br />
    @Html.Label("Durum")
    @Html.TextBoxFor(x => x.Status, new { @class = "form-control" })
    <br />
    @Html.Label("Yetki")
    @Html.TextBoxFor(x => x.Role, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Ekle</button>
</div>
}

MvcKamp/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table  table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Adı</th>
        <th>Yetki</th>
        <th>Durum</th>
        <th>Güncelle</th>
        
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.Id</th>
            <td>@item.UserName</td>
            <td>@item.Role</td>
            <td>@item.Status</td>
       
            <td><a href="/Authorization/UpdateAdmin/@item.Id" class="btn btn-primary">Bilgileri Güncelle</a></td>
            

        </tr>
    }
</table>
<br />
<a href="/Authorization/AddAdmin" class="btn btn-success">Yeni Admin Ekle</a>

MvcKamp/Views/Authorization/UpdateAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "UpdateAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Admin Güncelleme</h2>
@using (Html.BeginForm("UpdateAdmin", "Authorization", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.Id, new { @class = "form-control" })
    <br />
    @Html.Label("Kullanıcı Adı")
    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
    <br />
    @Html.Label("Şifre")
    @Html.TextAreaFor(x => x.Password, new { @class = "form-control" })
    <br />
    @Html.Label("Yetki")
    @Html.TextAreaFor(x => x.Role, new { @class = "form-control" })
    <br />
    @Html.Label("Durum")
    @Html.TextAreaFor(x => x.Status, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}